# Generated by Django 5.2.5 on 2025-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('success', 'success'), ('income', 'income')], default='success', max_length=20),
        ),
    ]
