# Generated by Django 5.2.5 on 2025-08-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('expense', 'expense'), ('income', 'income')], default='income', max_length=20),
        ),
    ]
