# Generated by Django 5.2.5 on 2025-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('failed', 'failed'), ('success', 'success'), ('blocked', 'blocked')], default='progress', max_length=20),
        ),
    ]
