# Generated by Django 5.2.5 on 2025-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymenthistory_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('failed', 'failed'), ('success', 'success'), ('blocked', 'blocked'), ('cancelled', 'cancelled')], default='progress', max_length=20),
        ),
    ]
