# Generated by Django 5.2.5 on 2025-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fees',
            field=models.FloatField(default=0.0),
        ),
    ]
