# Generated by Django 5.2.5 on 2025-08-15 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_adopted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
