# Generated by Django 5.2.5 on 2025-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_adoption_created_at_adoption_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
