# Generated by Django 5.2.5 on 2025-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_pet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
