# Generated by Django 5.2.5 on 2025-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
