# Generated by Django 5.2.5 on 2025-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='01912345678', max_length=14),
            preserve_default=False,
        ),
    ]
